BEGIN;

-- 1. Eski test data inactive qilish
UPDATE users SET is_active=false WHERE id BETWEEN 1 AND 15;

-- 2. Role yangilash
UPDATE users SET role='admin' WHERE id=16;
UPDATE users SET role='prorektor' WHERE id=17;
UPDATE users SET role='prorektor' WHERE id=18;
UPDATE users SET role='prorektor' WHERE id=19;
UPDATE users SET role='prorektor' WHERE id=20;
UPDATE users SET role='admin' WHERE id=29;

-- 3. Department / Position / Rank / Supervisor yangilash
UPDATE staff_profiles SET department='Rektorat', position='Rektor', rank='Rektor', supervisor_id=NULL, updated_at=NOW() WHERE user_id=16;
UPDATE staff_profiles SET department='Rektorat', position='Birinchi prorektor', rank='Prorektor', supervisor_id=16, updated_at=NOW() WHERE user_id=17;
UPDATE staff_profiles SET department='Rektorat', position='O''quv ishlari prorektori', rank='Prorektor', supervisor_id=16, updated_at=NOW() WHERE user_id=18;
UPDATE staff_profiles SET department='Rektorat', position='Yoshlar masalalari prorektori', rank='Prorektor', supervisor_id=16, updated_at=NOW() WHERE user_id=19;
UPDATE staff_profiles SET department='Rektorat', position='Moliya ishlari prorektori', rank='Prorektor', supervisor_id=16, updated_at=NOW() WHERE user_id=20;
UPDATE staff_profiles SET department='Rektorat', position='Rektor maslahatchisi', rank='Maslahatchi', supervisor_id=16, updated_at=NOW() WHERE user_id=21;
UPDATE staff_profiles SET department='Rektorat', position='Xorijiy hamkorlik maslahatchisi', rank='Maslahatchi', supervisor_id=16, updated_at=NOW() WHERE user_id=22;
UPDATE staff_profiles SET department='Rektorat', position='Matbuot kotibi', rank='Kotib', supervisor_id=16, updated_at=NOW() WHERE user_id=23;
UPDATE staff_profiles SET department='Ta''lim sifatini nazorat qilish bo''limi', position='Bosh mutaxassis', rank='Bosh mutaxassis', supervisor_id=18, updated_at=NOW() WHERE user_id=24;
UPDATE staff_profiles SET department='Yuridik murojaatlar bo''limi', position='Bo''lim boshlig''i', rank='Boshlig''i', supervisor_id=16, updated_at=NOW() WHERE user_id=25;
UPDATE staff_profiles SET department='Inson resurslarini boshqarish departamenti', position='Departament boshlig''i', rank='Boshlig''i', supervisor_id=16, updated_at=NOW() WHERE user_id=26;
UPDATE staff_profiles SET department='Inson resurslarini boshqarish departamenti', position='Bosh mutaxassis', rank='Bosh mutaxassis', supervisor_id=26, updated_at=NOW() WHERE user_id=27;
UPDATE staff_profiles SET department='Raqamli texnologiyalar bo''limi', position='Bo''lim boshlig''i', rank='Boshlig''i', supervisor_id=16, updated_at=NOW() WHERE user_id=28;
UPDATE staff_profiles SET department='Raqamli texnologiyalar bo''limi', position='Muhandis-dasturchi', rank='Muhandis', supervisor_id=28, updated_at=NOW() WHERE user_id=29;
UPDATE staff_profiles SET department='Raqamli texnologiyalar bo''limi', position='Veb-dizayner', rank='Dizayner', supervisor_id=28, updated_at=NOW() WHERE user_id=30;
UPDATE staff_profiles SET department='Axborot-resurs markazi', position='Kutubxonachi', rank='Kutubxonachi', supervisor_id=16, updated_at=NOW() WHERE user_id=31;
UPDATE staff_profiles SET department='Axborot-resurs markazi', position='Kutubxonachi', rank='Kutubxonachi', supervisor_id=16, updated_at=NOW() WHERE user_id=32;
UPDATE staff_profiles SET department='Registrator ofisi — Xizmat ko''rsatish bo''limi', position='Bo''lim boshlig''i', rank='Boshlig''i', supervisor_id=18, updated_at=NOW() WHERE user_id=33;
UPDATE staff_profiles SET department='Registrator ofisi — Ma''lumotlar bazasi bo''limi', position='Menejer', rank='Menejer', supervisor_id=38, updated_at=NOW() WHERE user_id=34;
UPDATE staff_profiles SET department='Registrator ofisi — Xizmat ko''rsatish bo''limi', position='Menejer', rank='Menejer', supervisor_id=33, updated_at=NOW() WHERE user_id=35;
UPDATE staff_profiles SET department='Registrator ofisi — Xizmat ko''rsatish bo''limi', position='Menejer', rank='Menejer', supervisor_id=33, updated_at=NOW() WHERE user_id=36;
UPDATE staff_profiles SET department='Registrator ofisi — Ma''lumotlar bazasi bo''limi', position='Muhandis-dasturchi', rank='Muhandis', supervisor_id=38, updated_at=NOW() WHERE user_id=37;
UPDATE staff_profiles SET department='Registrator ofisi — Ma''lumotlar bazasi bo''limi', position='Bo''lim boshlig''i', rank='Boshlig''i', supervisor_id=18, updated_at=NOW() WHERE user_id=38;
UPDATE staff_profiles SET department='Registrator ofisi — Ma''lumotlar bazasi bo''limi', position='Uslubchi', rank='Uslubchi', supervisor_id=38, updated_at=NOW() WHERE user_id=39;
UPDATE staff_profiles SET department='Registrator ofisi — Ma''lumotlar bazasi bo''limi', position='Menejer', rank='Menejer', supervisor_id=38, updated_at=NOW() WHERE user_id=40;
UPDATE staff_profiles SET department='Registrator ofisi — Ma''lumotlar bazasi bo''limi', position='Dispetcher', rank='Dispetcher', supervisor_id=38, updated_at=NOW() WHERE user_id=41;
UPDATE staff_profiles SET department='Registrator ofisi — Ma''lumotlar bazasi bo''limi', position='Katta dispetcher', rank='Dispetcher', supervisor_id=38, updated_at=NOW() WHERE user_id=42;
UPDATE staff_profiles SET department='Registrator ofisi — Ma''lumotlar bazasi bo''limi', position='Arxivarius', rank='Arxivarius', supervisor_id=38, updated_at=NOW() WHERE user_id=43;
UPDATE staff_profiles SET department='Registrator ofisi — Ma''lumotlar bazasi bo''limi', position='Mutaxassis', rank='Mutaxassis', supervisor_id=38, updated_at=NOW() WHERE user_id=44;
UPDATE staff_profiles SET department='Registrator ofisi — Ma''lumotlar bazasi bo''limi', position='Inspektor', rank='Inspektor', supervisor_id=38, updated_at=NOW() WHERE user_id=45;
UPDATE staff_profiles SET department='Talabalar bilan ishlash departamenti', position='Departament boshlig''i', rank='Boshlig''i', supervisor_id=19, updated_at=NOW() WHERE user_id=46;
UPDATE staff_profiles SET department='Talabalar bilan ishlash departamenti', position='Departament boshlig''i o''rinbosari', rank='O''rinbosar', supervisor_id=46, updated_at=NOW() WHERE user_id=47;
UPDATE staff_profiles SET department='Talabalar bilan ishlash departamenti', position='Dispetcher', rank='Dispetcher', supervisor_id=46, updated_at=NOW() WHERE user_id=48;
UPDATE staff_profiles SET department='Talabalar bilan ishlash departamenti', position='Tyutor', rank='Tyutor', supervisor_id=46, updated_at=NOW() WHERE user_id=49;
UPDATE staff_profiles SET department='Talabalar bilan ishlash departamenti', position='Tyutor', rank='Tyutor', supervisor_id=46, updated_at=NOW() WHERE user_id=50;
UPDATE staff_profiles SET department='Talabalar bilan ishlash departamenti', position='Tyutor', rank='Tyutor', supervisor_id=46, updated_at=NOW() WHERE user_id=51;
UPDATE staff_profiles SET department='Talabalar bilan ishlash departamenti', position='Tyutor', rank='Tyutor', supervisor_id=46, updated_at=NOW() WHERE user_id=52;
UPDATE staff_profiles SET department='Talabalar bilan ishlash departamenti', position='Tyutor', rank='Tyutor', supervisor_id=46, updated_at=NOW() WHERE user_id=53;
UPDATE staff_profiles SET department='Talabalar bilan ishlash departamenti', position='Tyutor', rank='Tyutor', supervisor_id=46, updated_at=NOW() WHERE user_id=54;
UPDATE staff_profiles SET department='Talabalar bilan ishlash departamenti', position='Tyutor', rank='Tyutor', supervisor_id=46, updated_at=NOW() WHERE user_id=55;
UPDATE staff_profiles SET department='Magistratura bo''limi', position='Uslubchi', rank='Uslubchi', supervisor_id=18, updated_at=NOW() WHERE user_id=56;
UPDATE staff_profiles SET department='Ilmiy tadqiqot va innovatsiyalar bo''limi', position='Bo''lim boshlig''i', rank='Boshlig''i', supervisor_id=18, updated_at=NOW() WHERE user_id=57;
UPDATE staff_profiles SET department='Xo''jalik bo''limi', position='Komendant', rank='Komendant', supervisor_id=20, updated_at=NOW() WHERE user_id=58;
UPDATE staff_profiles SET department='Xo''jalik bo''limi', position='Komendant', rank='Komendant', supervisor_id=20, updated_at=NOW() WHERE user_id=59;
UPDATE staff_profiles SET department='Xo''jalik bo''limi', position='Farrosh', rank='Farrosh', supervisor_id=20, updated_at=NOW() WHERE user_id=60;
UPDATE staff_profiles SET department='Xo''jalik bo''limi', position='Farrosh', rank='Farrosh', supervisor_id=20, updated_at=NOW() WHERE user_id=61;
UPDATE staff_profiles SET department='Xo''jalik bo''limi', position='Farrosh', rank='Farrosh', supervisor_id=20, updated_at=NOW() WHERE user_id=62;
UPDATE staff_profiles SET department='Xo''jalik bo''limi', position='Farrosh', rank='Farrosh', supervisor_id=20, updated_at=NOW() WHERE user_id=63;
UPDATE staff_profiles SET department='Buxgalteriya', position='Bosh hisobchi', rank='Bosh hisobchi', supervisor_id=20, updated_at=NOW() WHERE user_id=64;
UPDATE staff_profiles SET department='Buxgalteriya', position='Hisobchi', rank='Hisobchi', supervisor_id=64, updated_at=NOW() WHERE user_id=65;
UPDATE staff_profiles SET department='Ta''limning kredit tizimi bo''limi', position='Mutaxassis', rank='Mutaxassis', supervisor_id=18, updated_at=NOW() WHERE user_id=66;
UPDATE staff_profiles SET department='Ta''limning kredit tizimi bo''limi', position='Mutaxassis', rank='Mutaxassis', supervisor_id=18, updated_at=NOW() WHERE user_id=67;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='Kafedra mudiri', rank='Kafedra mudiri', supervisor_id=18, updated_at=NOW() WHERE user_id=68;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=69;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=70;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='Professor', rank='Professor', supervisor_id=68, updated_at=NOW() WHERE user_id=71;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=72;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=73;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='Dotsent', rank='Dotsent', supervisor_id=68, updated_at=NOW() WHERE user_id=74;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=75;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=76;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='Professor', rank='Professor', supervisor_id=68, updated_at=NOW() WHERE user_id=77;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='Dotsent', rank='Dotsent', supervisor_id=68, updated_at=NOW() WHERE user_id=78;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=79;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=80;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=81;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=82;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=83;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=84;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=85;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=86;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=87;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='Dotsent', rank='Dotsent', supervisor_id=68, updated_at=NOW() WHERE user_id=88;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='Dotsent', rank='Dotsent', supervisor_id=68, updated_at=NOW() WHERE user_id=89;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=90;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=91;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=92;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=93;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=94;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=95;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=96;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=97;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=98;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='Dotsent', rank='Dotsent', supervisor_id=68, updated_at=NOW() WHERE user_id=99;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=100;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=101;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=102;
UPDATE staff_profiles SET department='Pedagogika, psixologiya va sport kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=68, updated_at=NOW() WHERE user_id=103;
UPDATE staff_profiles SET department='Axborot texnologiyalari va amaliy fanlar kafedrasi', position='Kafedra mudiri', rank='Kafedra mudiri', supervisor_id=18, updated_at=NOW() WHERE user_id=104;
UPDATE staff_profiles SET department='Axborot texnologiyalari va amaliy fanlar kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=104, updated_at=NOW() WHERE user_id=105;
UPDATE staff_profiles SET department='Axborot texnologiyalari va amaliy fanlar kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=104, updated_at=NOW() WHERE user_id=106;
UPDATE staff_profiles SET department='Axborot texnologiyalari va amaliy fanlar kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=104, updated_at=NOW() WHERE user_id=107;
UPDATE staff_profiles SET department='Axborot texnologiyalari va amaliy fanlar kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=104, updated_at=NOW() WHERE user_id=108;
UPDATE staff_profiles SET department='Axborot texnologiyalari va amaliy fanlar kafedrasi', position='O''qituvchi (o''rindosh)', rank='O''qituvchi', supervisor_id=104, updated_at=NOW() WHERE user_id=109;
UPDATE staff_profiles SET department='Axborot texnologiyalari va amaliy fanlar kafedrasi', position='O''qituvchi (o''rindosh)', rank='O''qituvchi', supervisor_id=104, updated_at=NOW() WHERE user_id=110;
UPDATE staff_profiles SET department='Axborot texnologiyalari va amaliy fanlar kafedrasi', position='O''qituvchi (o''rindosh)', rank='O''qituvchi', supervisor_id=104, updated_at=NOW() WHERE user_id=111;
UPDATE staff_profiles SET department='Muhandislik va logistika kafedrasi', position='Kafedra mudiri', rank='Dotsent', supervisor_id=18, updated_at=NOW() WHERE user_id=112;
UPDATE staff_profiles SET department='Muhandislik va logistika kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=112, updated_at=NOW() WHERE user_id=113;
UPDATE staff_profiles SET department='Muhandislik va logistika kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=112, updated_at=NOW() WHERE user_id=114;
UPDATE staff_profiles SET department='Muhandislik va logistika kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=112, updated_at=NOW() WHERE user_id=115;
UPDATE staff_profiles SET department='Muhandislik va logistika kafedrasi', position='O''qituvchi (o''rindosh)', rank='O''qituvchi', supervisor_id=112, updated_at=NOW() WHERE user_id=116;
UPDATE staff_profiles SET department='Iqtisodiyot va moliyaviy texnologiyalar kafedrasi', position='Kafedra mudiri', rank='Dotsent', supervisor_id=18, updated_at=NOW() WHERE user_id=117;
UPDATE staff_profiles SET department='Iqtisodiyot va moliyaviy texnologiyalar kafedrasi', position='Vaqtbay dotsent', rank='Vaqtbay dotsent', supervisor_id=117, updated_at=NOW() WHERE user_id=118;
UPDATE staff_profiles SET department='Iqtisodiyot va moliyaviy texnologiyalar kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=117, updated_at=NOW() WHERE user_id=119;
UPDATE staff_profiles SET department='Iqtisodiyot va moliyaviy texnologiyalar kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=117, updated_at=NOW() WHERE user_id=120;
UPDATE staff_profiles SET department='Iqtisodiyot va moliyaviy texnologiyalar kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=117, updated_at=NOW() WHERE user_id=121;
UPDATE staff_profiles SET department='Iqtisodiyot va moliyaviy texnologiyalar kafedrasi', position='Vaqtbay dotsent', rank='Vaqtbay dotsent', supervisor_id=117, updated_at=NOW() WHERE user_id=122;
UPDATE staff_profiles SET department='Iqtisodiyot va moliyaviy texnologiyalar kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=117, updated_at=NOW() WHERE user_id=123;
UPDATE staff_profiles SET department='Iqtisodiyot va moliyaviy texnologiyalar kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=117, updated_at=NOW() WHERE user_id=124;
UPDATE staff_profiles SET department='Iqtisodiyot va moliyaviy texnologiyalar kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=117, updated_at=NOW() WHERE user_id=125;
UPDATE staff_profiles SET department='Iqtisodiyot va moliyaviy texnologiyalar kafedrasi', position='O''qituvchi', rank='O''qituvchi', supervisor_id=117, updated_at=NOW() WHERE user_id=126;
UPDATE staff_profiles SET department='Iqtisodiyot va moliyaviy texnologiyalar kafedrasi', position='PhD. Dotsent (o''rindosh)', rank='PhD, Dotsent', supervisor_id=117, updated_at=NOW() WHERE user_id=127;
UPDATE staff_profiles SET department='Iqtisodiyot va moliyaviy texnologiyalar kafedrasi', position='O''qituvchi (o''rindosh)', rank='O''qituvchi', supervisor_id=117, updated_at=NOW() WHERE user_id=128;
UPDATE staff_profiles SET department='Iqtisodiyot va moliyaviy texnologiyalar kafedrasi', position='O''qituvchi (o''rindosh)', rank='O''qituvchi', supervisor_id=117, updated_at=NOW() WHERE user_id=129;
UPDATE staff_profiles SET department='Iqtisodiyot va moliyaviy texnologiyalar kafedrasi', position='PhD. Dotsent (o''rindosh)', rank='PhD, Dotsent', supervisor_id=117, updated_at=NOW() WHERE user_id=130;

-- 4. Contract type
UPDATE staff_profiles SET contract_type='doimiy' WHERE user_id BETWEEN 16 AND 130 AND contract_type IS NULL;
UPDATE staff_profiles SET contract_type='shartnoma' WHERE user_id=109;
UPDATE staff_profiles SET contract_type='shartnoma' WHERE user_id=110;
UPDATE staff_profiles SET contract_type='shartnoma' WHERE user_id=111;
UPDATE staff_profiles SET contract_type='shartnoma' WHERE user_id=116;
UPDATE staff_profiles SET contract_type='shartnoma' WHERE user_id=127;
UPDATE staff_profiles SET contract_type='shartnoma' WHERE user_id=128;
UPDATE staff_profiles SET contract_type='shartnoma' WHERE user_id=129;
UPDATE staff_profiles SET contract_type='shartnoma' WHERE user_id=130;

COMMIT;