services:
  biu-postgres:
    image: postgres:16-alpine
    container_name: biu-postgres
    environment:
      POSTGRES_DB: BuiSmartApp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asfan2005
    ports:
      - "5433:5432"
    volumes:
      - biu_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  biu-backend:
    build: .
    container_name: biu-backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      NODE_ENV: production
      DB_HOST: biu-postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: asfan2005
      DB_NAME: BuiSmartApp
      JWT_SECRET: ddf743c2a21785d833cc79036428e56e7fc4cc9d9e56d491f0eab0258b3f3c2307e302ffbba395f8127d4f04032fe6dad112be11e1433ce01ef6a5c397ec6c38
      JWT_EXPIRES_IN: 7d
      CLIENT_URL: https://impaired-guidance-inexpensive-april.trycloudflare.com
    depends_on:
      - biu-postgres
    restart: unless-stopped

  biu-pgadmin:
    image: dpage/pgadmin4
    container_name: biu-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@biu.uz
      PGADMIN_DEFAULT_PASSWORD: asfan2005
    ports:
      - "5050:80"
    depends_on:
      - biu-postgres
    restart: unless-stopped

volumes:
  biu_postgres_data:
